# -*- coding: utf-8 -*-
"""python-scraping-kadai2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1quP6tRGc2sATIwf8DFALesO9uj3K0ntk
"""

!pip install requests

import requests
import pprint
from getpass import getpass

# APIキーの入力
api_key = getpass('APIキーを入力して下さい')

# 駅名の入力
station_word = input('駅名を入力して下さい')

# Google MapのURL
url = 'https://maps.googleapis.com/maps/api/geocode/json'

# 取得したデータに各値を代入
response = requests.get(
    url,
    params={
        'key':api_key, # APIキー
        'address':station_word # 駅名
    }
)

# 緯度経度を変数に格納
json_data = response.json()
for result in json_data['results']:
  latitude = result['geometry']['location']['lat']
  longitude = result['geometry']['location']['lng']

latlng = str(latitude) + ',' + str(longitude)

# 周辺の店舗を検索
url2 = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

response2 = requests.get(
    url2,
    params={
        'location':latlng,
        'language':'ja',
        'radius':'500',
        'type':'restaurant',
        'key':api_key
    }
)

# 検索結果の店名評価住所を変数に格納
json_data2 = response2.json()

for result in json_data2['results']:
  name = result['name']
  address = result['vicinity']
  rating = result['rating']
  print(f'{name} {rating} {address}')