# -*- coding: utf-8 -*-
"""python-scraping-kadai1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1er3q2GeA-aurZe85AcTKZ76DGpcArcks
"""

# 対象サイトを取得
!pip install requests

import requests
url = "https://news.yahoo.co.jp/articles/a12fab12de72e183c5562e11e78279a007c871e6"
response = requests.get(url)
html = response.text

# 対象サイトのHTMLを解析
!pip install beautifulsoup4

from bs4 import BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')
p_element = soup.select_one('#uamods > div.article_body.highLightSearchTarget > div:nth-child(1) > p')
p_text = p_element.text

# 表示
print(p_text)